
 
CREATE TABLE test_input.test30_input(
  MD_INSERTED_AT      TIMESTAMP NOT NULL ,
  F1_BK_AAA_VARCHAR      VARCHAR(20) ,
  F2_BK_AAA_DECIMAL      DECIMAL(20,0) ,
  F3_DC_AAA_DDD_VARCHAR      DATE NOT NULL ,
  F4_AAA_DDD_SP1_DECIMAL      DECIMAL(5,0) ,
  F5_AAA_DDD_SP1_DECIMAL      DECIMAL(5,0) 
);

